### ISSUE TITLE
Serving on different ports

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#5]
As discussed in https://github.com/saferactive/saferactive/issues/7. We should document how to serve the results on a different port. Vested interest: Port 80 is not available on my work desktop and I'd like to be able to reproduce the results here (could always use a laptop but think it's worth doing).

**Comment by layik** [comment]
1. Change front and back to default 8000, for now writing scripts to run on any port is not necessary and really adds nothing to the research

2. Change README to reflect (1)

**Comment by layik** [comment]
Separate ticket for rerex @Robinlovelace: https://github.com/saferactive/saferactive-eatlas/issues/6

It was always reproducible, just better ways of "fixing" things.

**Comment by layik** [comment]
This is about running the whole app on ~separate ports~ a port and making sure front queries this user given port, and this has little value right now. 

For separate processes (front and back), geoplumber runs both front and backend on any port. It is up to the programmer to make sure they speak to each other as this is not a Shiny/closed app. It is decoupled by design.

There is little more to be done than the commit.

**Comment by Robinlovelace** [comment]
One to document in the README? That could fix it I think...

**Comment by layik** [comment]
reopen if need be. Not an issue anymore.
